### ISSUE TITLE
Limit full scan run on Zuul on PRs to main

### ISSUE THREAD

**Issue by bitkeks** [SovereignCloudStack/security-infra-scan-pipeline#14]
Currently, even a commit with a LICENSE update triggers the full run of Zuul pipelines. We should limit this to only run, when relevant files are going to be merged onto main.

**Comment by gtema** [comment]
this is not a problem right now - test cloud is not providing working VMs as of now and as such all jobs running on VMs are not able to start.

**Comment by 90n20** [comment]
Fixed with #20
